// <auto-generated />
namespace ConsumptionSite.DataContexts.Migrations.Entities
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConsumptionRangeNavigationProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConsumptionRangeNavigationProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201704262258294_Consumption Range Navigation Property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
