using System.Web;

namespace ConsumptionSite.Handlers
{
	public class SampleHandler : IHttpHandler
	{
		public void ProcessRequest(HttpContext context)
		{
			context.Response.Write("<p>This was generated by the sample handler.</p>");
		}

		public bool IsReusable => false;
	}
}